version: '2'
services:
  mongo:
    image: wuzhongyang/test/mongo 
    container_name: mongo-wallbreaker-${DEV_USER}
    volumes: 
      - ../mongodb:/data/db
      - ../www/database/mongo:/var/www/mongo
    expose:
      - "27017"
  fpm:
    environment:
      - DEBUG=true
    image: qihoo.cloud/qssweb/abtest-php:0.5.0-base
    container_name: fpm-wallbreaker-${DEV_USER}
    volumes:
      # 挂载项目代码目录
      - ../www:/var/www/html/www
    links:
      # 关联容器, 在该容器中可以通过 `fpm.localhost` 域名访问另一个容器的端口
      - mongo:mongo.localhost
    expose:
      - "9000"

  nginx:
    image: qihoo.cloud/library/nginx
    container_name: nginx-wallbreaker-${DEV_USER}
    volumes:
      # 加载项目nginx配置
      - ./nginx.conf:/etc/nginx/conf.d/php.conf:ro
      # 挂载项目代码目录
      - ../www:/var/www/html/www:ro
    links:
      # 关联容器, 在该容器中可以通过 `fpm.localhost` 域名访问另一个容器的端口
      - fpm:fpm.localhost
    ports:
      - "${DEV_PORT}:8000"

