version: '2'
services:
  #mongo:
  #  image: wzy.cloud/library/mongo:3.2 
  #  container_name: mongo-wallbreaker-${DEV_USER}
  #  volumes: 
  #    - ../mongodb:/data/db
  #    - ../www/database/mongo:/var/www/mongo
  #  expose:
  #    - "27017"
  fpm:
    environment:
      - DEBUG=true
    image: wzy.cloud/php-phalcon 
    container_name: fpm-wallbreaker-${DEV_USER}
    volumes:
      # 挂载项目代码目录
      - ../www:/var/www/html/www
    # links:
      # 关联容器, 在该容器中可以通过 `fpm.localhost` 域名访问另一个容器的端口
      # - mongo:mongo.localhost
    expose:
      - "9000"
  nginx:
    image: wzy.cloud/library/nginx:1.9.8 
    container_name: nginx-wallbreaker-${DEV_USER}
    volumes:
      # 加载项目nginx配置
      - ./nginx.conf:/etc/nginx/conf.d/php.conf:ro
      # 挂载项目代码目录
      - ../www:/var/www/html/www:ro
    links:
      # 关联容器, 在该容器中可以通过 `fpm.localhost` 域名访问另一个容器的端口
      - fpm:fpm.localhost
    ports:
      - "${DEV_PORT}:8000"
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=123456 
    image: docker.io/mysql 
    container_name: mysql-${DEV_USER}
    volumes:
      - ../mysql:/var/lib/mysql
    ports:
      - "3306:3306"

